/**
 * Codicon name → Tabler icon lookup.
 *
 * `<Codicon name="...">` call sites (and the string-driven codicon names
 * threaded through project/profile/reference pickers) keep using VS Code's
 * codicon vocabulary as their identifier, but render through Tabler icons
 * instead of the `@vscode/codicons` glyph font — Douglas Agent's own icon
 * language rather than the inherited one.
 */

import {
  IconAlertCircle,
  IconAlertTriangle,
  IconArchive,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowsLeftRight,
  IconArrowsMinimize,
  IconArrowsMove,
  IconArrowUp,
  IconAt,
  IconBan,
  IconBolt,
  IconBook,
  IconBookmark,
  IconBraces,
  IconBriefcase,
  IconBroadcast,
  IconBrowser,
  IconBug,
  IconBuilding,
  IconBulb,
  IconChartLine,
  IconCheck,
  IconChecks,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircle,
  IconCircleCheckFilled,
  IconCircleMinus,
  IconClock,
  IconCloud,
  IconCloudDownload,
  IconCloudUpload,
  IconCode,
  IconCompass,
  IconCopy,
  IconCpu,
  IconCreditCard,
  IconDatabase,
  IconDeviceDesktop,
  IconDeviceFloppy,
  IconDeviceMobile,
  IconDots,
  IconDotsVertical,
  IconDownload,
  IconEdit,
  IconEraser,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFiles,
  IconFilter,
  IconFlame,
  IconFlask,
  IconFolder,
  IconFolderCode,
  IconFolderOpen,
  IconFolderPlus,
  IconFolderRoot,
  IconFolders,
  IconGift,
  IconGitBranch,
  IconGitCompare,
  IconGitFork,
  IconGitMerge,
  IconGitPullRequest,
  IconGripVertical,
  IconHeart,
  IconHelpCircle,
  IconHistory,
  IconHome,
  IconInbox,
  IconInfoCircle,
  IconKey,
  IconKeyboard,
  IconLayout,
  IconLayoutColumns,
  IconLayoutDashboard,
  IconLayoutSidebar,
  IconLayoutSidebarRight,
  IconLink,
  IconList,
  IconListCheck,
  IconListDetails,
  IconListTree,
  IconLoader2,
  IconMenu2,
  IconMessage,
  IconMessageDots,
  IconMessagePlus,
  IconMessages,
  IconMicrophone,
  IconMinus,
  IconMoodSmile,
  IconPackage,
  IconPalette,
  IconPencil,
  IconPhoto,
  IconPin,
  IconPlayerPause,
  IconPlayerPlay,
  IconPlayerPlayFilled,
  IconPlayerStop,
  IconPlug,
  IconPlugConnectedX,
  IconPlus,
  IconPuzzle,
  IconRefresh,
  IconRobot,
  IconRocket,
  IconRotate,
  IconSearch,
  IconSelect,
  IconServer,
  IconServerCog,
  IconSettings,
  IconShape,
  IconShield,
  IconSparkles,
  IconSpeakerphone,
  IconSquareRoundedMinus,
  IconSquareRoundedPlus,
  IconSquareX,
  IconStack2,
  IconStarFilled,
  IconTarget,
  IconTelescope,
  IconTerminal2,
  IconTextSize,
  IconTool,
  IconTrash,
  IconTrashX,
  IconUserCircle,
  IconVolume,
  IconVolumeOff,
  IconWifi,
  IconWindow,
  IconWorld,
  IconX
} from '@tabler/icons-react'
import type { Icon } from '@tabler/icons-react'

export const CODICON_GLYPHS: Record<string, Icon> = {
  account: IconUserCircle,
  add: IconPlus,
  agent: IconRobot,
  alert: IconAlertTriangle,
  archive: IconArchive,
  'arrow-down': IconArrowDown,
  'arrow-left': IconArrowLeft,
  'arrow-right': IconArrowRight,
  'arrow-swap': IconArrowsLeftRight,
  'arrow-up': IconArrowUp,
  beaker: IconFlask,
  book: IconBook,
  bookmark: IconBookmark,
  broadcast: IconBroadcast,
  browser: IconBrowser,
  bug: IconBug,
  check: IconCheck,
  'check-all': IconChecks,
  checklist: IconListCheck,
  'chevron-down': IconChevronDown,
  'chevron-left': IconChevronLeft,
  'chevron-right': IconChevronRight,
  'chevron-up': IconChevronUp,
  chip: IconCpu,
  'circle-outline': IconCircle,
  'circle-slash': IconBan,
  'clear-all': IconEraser,
  close: IconX,
  'close-all': IconSquareX,
  cloud: IconCloud,
  'cloud-download': IconCloudDownload,
  'cloud-upload': IconCloudUpload,
  'collapse-all': IconArrowsMinimize,
  'color-mode': IconPalette,
  comment: IconMessage,
  'comment-discussion': IconMessages,
  compass: IconCompass,
  copy: IconCopy,
  'credit-card': IconCreditCard,
  dash: IconMinus,
  dashboard: IconLayoutDashboard,
  database: IconDatabase,
  'debug-disconnect': IconPlugConnectedX,
  'debug-pause': IconPlayerPause,
  'debug-restart': IconRotate,
  'device-desktop': IconDeviceDesktop,
  'device-mobile': IconDeviceMobile,
  diff: IconGitCompare,
  'diff-added': IconSquareRoundedPlus,
  'diff-modified': IconPencil,
  'diff-removed': IconSquareRoundedMinus,
  'diff-renamed': IconArrowRight,
  discard: IconTrashX,
  download: IconDownload,
  edit: IconPencil,
  ellipsis: IconDots,
  error: IconAlertCircle,
  exclude: IconCircleMinus,
  extensions: IconPuzzle,
  eye: IconEye,
  'eye-closed': IconEyeOff,
  file: IconFile,
  'file-media': IconPhoto,
  files: IconFiles,
  filter: IconFilter,
  flame: IconFlame,
  folder: IconFolder,
  'folder-library': IconFolders,
  'folder-opened': IconFolderOpen,
  gift: IconGift,
  'git-branch': IconGitBranch,
  'git-pull-request': IconGitPullRequest,
  globe: IconWorld,
  grabber: IconGripVertical,
  graph: IconChartLine,
  gripper: IconGripVertical,
  heart: IconHeart,
  history: IconHistory,
  home: IconHome,
  hubot: IconRobot,
  inbox: IconInbox,
  info: IconInfoCircle,
  json: IconBraces,
  'kebab-vertical': IconDotsVertical,
  key: IconKey,
  keyboard: IconKeyboard,
  layers: IconStack2,
  layout: IconLayout,
  'layout-sidebar-left': IconLayoutSidebar,
  'layout-sidebar-right': IconLayoutSidebarRight,
  lightbulb: IconBulb,
  link: IconLink,
  'link-external': IconExternalLink,
  'list-flat': IconList,
  'list-selection': IconListDetails,
  'list-tree': IconListTree,
  'list-unordered': IconList,
  loading: IconLoader2,
  mcp: IconPlug,
  megaphone: IconSpeakerphone,
  menu: IconMenu2,
  mic: IconMicrophone,
  move: IconArrowsMove,
  mute: IconVolumeOff,
  'new-folder': IconFolderPlus,
  'new-session': IconMessagePlus,
  openai: IconSparkles,
  organization: IconBuilding,
  package: IconPackage,
  pass: IconCheck,
  'pass-filled': IconCircleCheckFilled,
  pin: IconPin,
  play: IconPlayerPlay,
  'play-circle': IconPlayerPlayFilled,
  plug: IconPlug,
  preview: IconWindow,
  project: IconBriefcase,
  question: IconHelpCircle,
  references: IconAt,
  refresh: IconRefresh,
  remote: IconWifi,
  remove: IconMinus,
  rename: IconEdit,
  repo: IconFolderCode,
  'repo-forked': IconGitFork,
  robot: IconRobot,
  rocket: IconRocket,
  'root-folder': IconFolderRoot,
  run: IconPlayerPlay,
  save: IconDeviceFloppy,
  search: IconSearch,
  selection: IconSelect,
  server: IconServer,
  'server-process': IconServerCog,
  settings: IconSettings,
  'settings-gear': IconSettings,
  shield: IconShield,
  smiley: IconMoodSmile,
  sparkle: IconSparkles,
  'split-horizontal': IconLayoutColumns,
  'star-full': IconStarFilled,
  stop: IconPlayerStop,
  'symbol-color': IconPalette,
  'symbol-misc': IconShape,
  sync: IconRefresh,
  target: IconTarget,
  telescope: IconTelescope,
  terminal: IconTerminal2,
  'text-size': IconTextSize,
  thinking: IconMessageDots,
  tools: IconTool,
  trash: IconTrash,
  'triangle-right': IconChevronRight,
  unmute: IconVolume,
  vscode: IconCode,
  warning: IconAlertTriangle,
  watch: IconClock,
  window: IconWindow,
  worktree: IconGitMerge,
  zap: IconBolt
}
